<AccelerometerScreen>:
    orientation: 'vertical'
    padding: 30
    spacing: 20

    Label:
        id: lbl_origem
        text: "Status: Inicializando..."
        font_size: '18sp'
        size_hint_y: None
        height: '40dp'
        halign: 'center'
        valign: 'middle'

    Label:
        id: lbl_dados
        text: "Eixo X: --\nEixo Y: --\nEixo Z: --"
        font_size: '22sp'
        halign: 'center'
        valign: 'middle'

    Label:
        id: lbl_magnitude
        text: "Magnitude: -- m/s²"
        font_size: '20sp'
        size_hint_y: None
        height: '50dp'
        halign: 'center'
        valign: 'middle'
